### ISSUE TITLE
Nest meta response key-values under `meta`

### ISSUE THREAD

**Issue by juanca** [mavenlink/brainstem#101]
Kinda weird that we have to whitelist in our JS libs. Would be nice to be able to do this programmatically. Nesting count, page info, and results under `meta` can facilitate this. 

Thoughts? We will need to be able to version our API or figure out how many other people use this.

**Comment by ahuth** [comment]
Yeah, I thought about this, but didn't come up with any great insights.

Some examples of APIs have a `meta` key, and others don't. Also, a 3rd option is to use response headers for some of the meta stuff.

**Comment by ahuth** [comment]
Did this in b01a220c1b98109462740bf5d4ffea848c9766b0

**Comment by juanca** [comment]
Awesome! Thanks for taking a lead on that.

I will now add a TODO to drop the redundant `count` for API v2.0
