### ISSUE TITLE
Ints cast as strings

### ISSUE THREAD

**Issue by vinnyglennon** [mavenlink/brainstem#50]
In your README example:
  widgets: {
    "10": {
      id: "10",
      name: "disco ball",
      feature_ids: ["5"],
      popularity: 85,
      location_id: "2"
    },

    "2": {
      id: "2",
      name: "flubber",
      feature_ids: ["6", "12"],
      popularity: 100,
      location_id: "2"
    }
  }

Is it possible to have *_id's as ints so that this would render as below? This would keep it consistent data types.
 
  widgets: {
    "10": {
      id: 10,
      name: "disco ball",
      feature_ids: [5],
      popularity: 85,
      location_id: 2
    },

    "2": {
      id: 2,
      name: "flubber",
      feature_ids: [6, 12],
      popularity: 100,
      location_id: 2
    }
  }

**Comment by cantino** [comment]
We try to always have ids as strings so that they can cleanly index into the JSON objects in JavaScript.  All hash keys should be strings in JS.
