### ISSUE TITLE
Bundler should work with a variety of ruby version

### ISSUE THREAD

**Issue by juanca** [mavenlink/brainstem#84]
> https://github.com/mavenlink/brainstem/pull/82#issuecomment-248426196

and

> https://github.com/bundler/bundler/issues/4960

Seems like the gem dependencies are not being resolved correctly. Once bundler gets some fix in, this should autofix itself here.

**Comment by ahuth** [comment]
@juanca, is this addressed in #89 ?

**Comment by juanca** [comment]
Uh, lemme check.

**Comment by juanca** [comment]
Well, nothing seems to have happen on the bundler side.

But our spec suite is green across our supported ruby version.

So I would say so.
