### ISSUE TITLE
Release Version 0.2.7

### ISSUE THREAD

**Issue by ahuth** [mavenlink/brainstem#90]
Current version of the gem is 0.2.6.1. What do you think, @shirish-pampoorickal, of releasing a 0.2.7 now because we dropped support for Ruby versions less than 2.1.10?

Then, when the API doc generation goes in, we can release 0.3, or maybe even 1.0.

**Comment by shirish-pampoorickal** [comment]
Sounds good to me! Lets bump it up to 0.2.7

**Comment by ahuth** [comment]
Bumping to 1.0.0.pre.1
